--------------------------------------------------------
--  파일이 생성됨 - 화요일-6월-22-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "SCOTT"."CUSTOMER" 
   (	"CNO" NUMBER(6,0), 
	"CNAME" VARCHAR2(25 BYTE), 
	"CBIRTH" DATE, 
	"CGRADE" VARCHAR2(6 BYTE), 
	"CENTER" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.CUSTOMER
SET DEFINE OFF;
Insert into SCOTT.CUSTOMER (CNO,CNAME,CBIRTH,CGRADE,CENTER) values (111111,'Solla',to_date('87/01/30','RR/MM/DD'),'Silver',to_date('05/03/09','RR/MM/DD'));
Insert into SCOTT.CUSTOMER (CNO,CNAME,CBIRTH,CGRADE,CENTER) values (222222,'Mat',to_date('70/02/15','RR/MM/DD'),'Silver',to_date('13/09/05','RR/MM/DD'));
Insert into SCOTT.CUSTOMER (CNO,CNAME,CBIRTH,CGRADE,CENTER) values (333333,'Mike',to_date('70/04/05','RR/MM/DD'),'Vip',to_date('15/10/02','RR/MM/DD'));
Insert into SCOTT.CUSTOMER (CNO,CNAME,CBIRTH,CGRADE,CENTER) values (444444,'Jake',to_date('88/05/02','RR/MM/DD'),'Gold',to_date('14/10/29','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007010
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C007010" ON "SCOTT"."CUSTOMER" ("CNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."CUSTOMER" ADD PRIMARY KEY ("CNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
